import React, { useState, useCallback } from "react";
import type { Metadata } from "next";
import Image from "next/image";
import AuthContent from "@/components/AuthContent";

export const metadata: Metadata = {
  title: "Headflix Auth",
  description: "Generated by create next app",
};

const Auth = () => {
  return (
    <div className="">
      <Image
        src="/images/logo.png"
        alt="logo"
        width={150}
        height={20}
        className="fixed top-2 left-4 cursor-pointer md:left-8 md:top-4"
      />
      <AuthContent />
    </div>
  );
};

export default Auth;
